[lib]
crate-type = [ "staticlib" ]

[package]
name = "swan_os"
version = "0.0.1"
edition = "2021"

[dependencies]
x86 = "0.52.0"
uart_16550 = "0.3.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.5.2"

[profile.release]
lto = true
opt-level = 2
strip = true